WEBAPI/HSchool/HSchool.Web/Controllers/ApplicationController.cs
using HSchool.Business.Models;
using HSchool.Business.Repository;
using HSchool.Common;
using HSchool.Logging;
using HSchool.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;

using HttpStatusCode = System.Net.HttpStatusCode;

namespace HSchool.Web.Controllers
{

    // GET: Application
    public class ApplicationController : Controller
    {
        #region Fields
        private readonly IAdminRepository _adminRepository;
        private readonly IStudentRepository _studentRepository;
        private readonly IApplicationRepository _applicationRepository;
        private readonly IClassRepository _classRepository;
        private ApplicationUserManager _userManager;
        #endregion

        #region Properties
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        #endregion

        #region Ctor
        /// <summary>
        /// 
        /// </summary>
        //public ApplicationController()
        //{

        //}

        /// <summary>
        /// 
        /// </summary>
        /// <param name="userManager"></param>
        /// <param name="adminRepository"></param>
        /// <param name="studentRepository"></param>
        /// <param name="applicationRepository"></param>
        public ApplicationController(ApplicationUserManager userManager, IAdminRepository adminRepository, IStudentRepository studentRepository, IApplicationRepository applicationRepository, IClassRepository classRepository)
        {
            _adminRepository = adminRepository;
            _studentRepository = studentRepository;
            _applicationRepository = applicationRepository;
            _classRepository = classRepository;
        }
        #endregion

        #region Actions
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            LogHelper.Info(string.Format("ApplicationController.Index - Begin"));
            try
            {
                var applicationForm = CreateApplicationForm(null, true);
                applicationForm.IsOfficeFormEnabled = false;
                applicationForm.IsStudentAddressUpdate = true;
                applicationForm.IsStudentGuardianUpdate = true;
                applicationForm.IsEditable = true;
                LogHelper.Info(string.Format("ApplicationController.Index - End"));
                return View(applicationForm);
            }
            catch (Exception ex)
            {
                LogHelper.Error(string.Format("ApplicationController.Index - Exception:{0}", ex.Message));
                return View("Error", ex.Message);
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        [CustomAuthentication]
        public ActionResult Details(int id)
        {
            LogHelper.Info(string.Format("ApplicationController.Details - Begin"));
            try
            {
                var applicationForm = _applicationRepository.GetApplicationById(id);
                applicationForm.IsEditable = false;
                LogHelper.Info(string.Format("ApplicationController.Details - End"));
                return View(applicationForm);
            }
            catch (Exception ex)
            {
                return View("Error", ex);
            }
        }

        /// <summary>
        /// To edit student information
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>        
        [HttpGet]
        public ActionResult Edit(int id)
        {
            LogHelper.Info(string.Format("ApplicationController.Edit - Begin"));
            try
            {
                var applicationForm = _applicationRepository.GetApplicationById(id);
                applicationForm.IsEditable = true;
                applicationForm.IsOfficeFormEnabled = false;
                LogHelper.Info(string.Format("ApplicationController.Edit - End"));
                return View(applicationForm);
            }
            catch (Exception ex)
            {
                return View("Error", ex);
            }
        }

        /// <summary>
        /// To edit office form only
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult OfficeForm(int id)
        {
            LogHelper.Info(string.Format("ApplicationController.EditOfficeForm - Begin"));
            try
            {
                var applicationForm = _applicationRepository.GetApplicationById(id);
                applicationForm.IsEditable = false;
                applicationForm.IsOfficeFormEnabled = true;
                LogHelper.Info(string.Format("ApplicationController.EditOfficeForm - End"));
                return View("Edit", applicationForm);
            }
            catch (Exception ex)
            {
                return View("Error", ex);
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ApplicationForm model, FormCollection collection)
        {
            LogHelper.Info(string.Format("ApplicationController.Edit - Begin"));
            try
            {
                int? id = null;
                MessageResponse response = null;
                //if (ModelState.IsValid)
                //{
                model.IsStudentUpdate = true;
                model.UserStatus = (int)UserStatusEnum.Registered;
                model.VisibleMark = false;
                model.ApplicationStatus = (int)ApplicationStatus.Submitted;
                model.IsTransportRequired = collection.GetFormValue<bool>("IsTransportRequired");
                id = _applicationRepository.SaveApplication(model);
                response = new MessageResponse<string>(id.HasValue ? id.ToString() : string.Empty, WebConstants.StatusSuccess, (int)HttpStatusCode.OK, string.Empty);
                //}
                //else
                //{
                //    response = new MessageResponse<string>(id.HasValue ? id.ToString() : string.Empty, WebConstants.StatusFailure, (int)HttpStatusCode.ExpectationFailed, "Invalid Request. Please validate the mandatory fields.");
                //}
                LogHelper.Info(string.Format("ApplicationController.Edit - End"));
                return Json(response, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                LogHelper.Info(string.Format("ApplicationController.Edit - Exception:{0}", ex.Message));
                var response = new MessageResponse<string>(string.Empty, WebConstants.StatusFailure, (int)HttpStatusCode.ExpectationFailed, ex.Message);
                return Json(response, JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <param name="collection"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditOfficeForm(ApplicationForm model, FormCollection collection)
        {
            LogHelper.Info(string.Format("ApplicationController.EditOfficeForm - Begin"));
            MessageResponse response = null;
            string responseMessage = string.Empty;
            try
            {
                if (ModelState.IsValid)
                {
                    bool userLoginEnabled = collection.GetFormValue<bool>("LoginEnabled");
                    //bool guardianLoginEnabled = collection.GetFormValue<bool>("GuardianLoginEnabled");                    
                    model.IsStudentUpdate = false;
                    //user details
                    if (userLoginEnabled)
                    {
                        model.Email = model.StudentGuardians.FirstOrDefault().Email;
                        model.Password = CommonHelper.CreateDefaultPassword(model.UserName, model.StudentGuardians.FirstOrDefault().DateOfBirth);
                        var user = new ApplicationUser { UserName = model.UserName, Email = model.Email };
                        var result = await UserManager.CreateAsync(user, model.Password);
                        if (result.Succeeded)
                        {
                            responseMessage = string.Format("{0}", "Login Enabled successfully.");
                        }
                    }
                    var applicationId = _applicationRepository.SaveApplication(model);
                    response = new MessageResponse<string>(responseMessage, WebConstants.StatusSuccess, (int)HttpStatusCode.OK, string.Empty);
                }
                LogHelper.Info(string.Format("ApplicationController.EditOfficeForm - End"));
                return Json(response, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                response = new MessageResponse<string>(ex.Message, WebConstants.StatusFailure, (int)HttpStatusCode.ExpectationFailed, ex.Message);

WEBAPI/HSchool/HSchool.Web/Views/Shared/_GridView.cshtml
<script type="text/x-jsrender" id="gridViewTemplate">
    <div class="">
        <table class="table">
            <thead>
                <tr>
                    {{for Columns}}
                    <th class="">{{:ColumnName}}</th>
                    {{/for}}
                </tr>
            </thead>

            {{for Rows}}
            <tr>
                {{for Cells}}
                <td class="">
                    {{:Value}}
                </td>
                {{/for}}
            </tr>
            {{/for}}
        </table>
    </div>
    <div class="pager">

    </div>
</script>

WEBAPI/HSchool/HSchool.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>HASHINY INTERNATIONAL MATRIC SCHOOL</title>
    <link href='https://fonts.googleapis.com/css?family=Orbitron:400,500,700,900' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Josefin+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/jquery.form.js")
    @Scripts.Render("~/Scripts/jquery.blockUI.js")
    @Scripts.Render("~/Scripts/jsrender.min.js")
    @Scripts.Render("~/bundles/custom")    
    @Scripts.Render("~/bundles/admin")
    <script src="~/Scripts/Application/Home.js"></script>

    <script type="text/javascript">
        var applicationRootUrl = "@(Url.Content("~/"))";
        $(document).ready(function () {
            //disabled the field
            $(".disableField").disabled();
            //Text Box Edit Animation
            $('.custom-text input[type="text"], .custom-text input[type="password"]').editAnimate();
            // Left menu expand collapse
            //$('.btn-expand-collapse').html('<i class="fa fa-angle-left></i>');
            $('.btn-expand-collapse').click(function () {
                $(this).find('i').toggleClass('fa-angle-left fa-angle-right');
                $('.left-panel').toggleClass('left-panel-expand');
            });
        });
    </script>
</head>
<body>
    <div class="ribbonErrorMessage" id="ribbonErrorMessage" style="display:none"></div>
    <div class="container-fluid content-wrapper clearfix">
        <div class="navbar set-radius-zero">
            <div class="navbar-header col-md-6">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">
                    <img src="~/Content/Images/app_name.png" />
                </a>
            </div>
            <div class="col-md-6">
                @Html.Partial("_LoginPartial")
            </div>
        </div>
        <section class="menu-section">
          
                    @Html.Partial("_MenuView")
          
        </section>
        <div class="body-wrapper">
            @RenderBody()
        </div>
    </div>
    <footer>
        <p>&copy; Hashiny International School @DateTime.Now.Year</p>
    </footer>
    <!-- Onvia progress bar -->
    <div id="ajaxProgressLoader" style="display: none;">
        <div class="loadingProgress">
            @*<img src="@(Url.Content("~/Content/Images/loading_2.gif"))" alt="processing.." class="loadingImage" />*@
            <i class="fa fa-spinner fa-spin fa-3x fa-fw"></i>
            <span id="additionalLoadingMessage"></span><span id="loadingMessage">Loading...</span>
        </div>
    </div>
    <!-- Onvia dialog -->
    <div id="OnviaAdminDialog">
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>

WEBAPI/HSchool/HSchool.Web/Views/Shared/_MenuView.cshtml
<nav class="navbar navbar-default">
    <div class="container-fluid">        

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home <span class="sr-only">(current)</span></a></li>
               
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Application <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Online Application</a></li>
                        <li><a href="#">Search</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Application Status</a></li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Admin</a></li>
                        <li><a href="#">Management</a></li>
                        <li><a href="#">Student</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">User</a></li>
                    </ul>
                </li>
               
                <li><a href="#">Link</a></li>
            </ul>
           
            
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

@*@if (Request.IsAuthenticated)
{
    <ul id="menu-top" class="nav navbar-nav navbar-right">
        <li>@Html.ActionLink("Home", "Index", "Home", new { }, new { })</li>
        <li><a href="#">Manage</a></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                Application <span class="caret"></span>
            </a>
            <ul class="dropdown" role="menu">
                <li>@Html.ActionLink("Online Application", "Index", "Application", new { }, new { })</li>
                <li>@Html.ActionLink("Search", "Search", "Application", new { }, new { })</li>
                <li>@Html.ActionLink("Application Status", "Status", "Application", new { }, new { })</li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                Admin <span class="caret"></span>
            </a>
            <ul class="dropdown" role="menu">
                <li>@Html.ActionLink("Admin", "Index", "Admin", new { }, new { })</li>
                <li>@Html.ActionLink("Management", "Management", "Admin", new { }, new { })</li>
                <li>@Html.ActionLink("Student", "Index", "Student", new { }, new { })</li>
                <li>@Html.ActionLink("User", "Index", "User", new { }, new { })</li>
            </ul>
        </li>
    </ul>
}
else
{
    <ul id="menu-top" class="nav navbar-nav navbar-right">
        <li>@Html.ActionLink("Home", "Index", "Home", new { }, new { })</li>
        <li>@Html.ActionLink("Application", "Index", "Application", new { }, new { })</li>
    </ul>
}*@